const translations = {
pt:{
"nav.about":"Sobre","nav.services":"Serviços","nav.why":"Diferenciais","nav.story":"História","nav.clients":"Clientes",
"hero.eyebrow":"Engenharia • Serviços • Soluções Integradas","hero.title":"Transformamos desafios em soluções práticas.","hero.text":"Serviços técnicos, industriais e de higienização com foco em qualidade, segurança, inovação e sustentabilidade.","hero.cta1":"Conheça os serviços","hero.cta2":"Quem somos","hero.point1":"Qualidade","hero.point2":"Segurança","hero.point3":"Sustentabilidade","hero.badge":"Excelência em serviços",
"about.eyebrow":"Quem somos","about.title":"Uma empresa jovem, multidisciplinar e orientada para resultados.","about.p1":"A Precise Planning Engenharia & Serviços, LDA (2PESL) é uma empresa inovadora criada para transformar desafios em oportunidades através de tecnologia, conhecimento técnico e soluções personalizadas.","about.p2":"A equipa é formada por profissionais dedicados, comprometidos com excelência, agilidade, melhoria contínua e gestão da qualidade, servindo clientes, parceiros e fornecedores com responsabilidade.",
"mission.title":"Missão","mission.text":"Oferecer serviços de alta qualidade, atuar de forma responsável e ética e inovar continuamente para superar as expectativas dos clientes.","vision.title":"Visão","vision.text":"Ser reconhecida nacionalmente como referência nas suas áreas de atuação, pela excelência dos serviços e compromisso com a responsabilidade social.","values.title":"Valores","values.text":"Transparência, excelência, qualificação profissional, sustentabilidade, inovação, ética e segurança.",
"services.eyebrow":"O que fazemos","services.title":"Serviços integrados para operações, infraestruturas e ambientes.","services.intro":"A atuação da 2PESL combina engenharia, suporte operacional, comércio e higienização especializada.",
"services.s1.t":"Planeamento Mineiro & Topografia","services.s1.d":"Planeamento mineiro, cálculo de reservas, topografia e serviços técnicos para otimizar operações e produtividade.","services.s2.t":"Construção & Infraestruturas","services.s2.d":"Projetos de construção civil, instalação elétrica, canalização, drenagem civil e industrial e serralharia.","services.s3.t":"Transporte & Logística","services.s3.d":"Prestação de serviços de transporte de carga e passageiros, com soluções adaptadas às necessidades do cliente.","services.s4.t":"Limpeza & Higienização","services.s4.d":"Limpeza de escritórios, residências, cabines de veículos e equipamentos, com desinfeção, neutralização de odores e manutenção regular.","services.s5.t":"Serviços Especiais de Higiene","services.s5.d":"Tratamentos antibacterianos e antifúngicos e programas de higienização personalizados para empresas e frotas.","services.s6.t":"Fornecimentos & Comércio","services.s6.d":"Fornecimento de material de escritório, jardinagem, comércio geral, atacado e varejo, importação e exportação de mercadorias.",
"clean.eyebrow":"Higienização especializada","clean.title":"Ambientes mais limpos, seguros e produtivos.","clean.text":"A abordagem de higienização combina profissionais treinados, equipamentos modernos e práticas ecológicas para oferecer um padrão elevado de limpeza.","clean.a":"Limpeza profunda de assentos, painéis e pisos","clean.b":"Desinfeção de superfícies de alto contacto","clean.c":"Limpeza de estações de trabalho e áreas comuns","clean.d":"Programas personalizados para empresas e frotas",
"why.eyebrow":"Porquê a 2PESL","why.title":"Diferenciais que sustentam a qualidade do serviço.","why.w1.t":"Equipa especializada","why.w1.d":"Profissionais treinados e qualificados para executar os serviços com eficiência e cuidado.","why.w2.t":"Práticas ecológicas","why.w2.d":"Utilização responsável de produtos e práticas que respeitam o ambiente e promovem a sustentabilidade.","why.w3.t":"Tecnologia e inovação","why.w3.d":"Adoção de equipamentos, métodos e soluções modernas para aumentar a eficácia e a rapidez.","why.w4.t":"Atendimento personalizado","why.w4.d":"Soluções ajustadas às necessidades específicas de cada operação, cliente e ambiente.",
"story.eyebrow":"Nossa história","story.title":"Crescimento construído sobre compromisso e excelência.","story.text":"Apesar de ser uma empresa jovem, a 2PESL já constrói uma trajetória marcada por conquistas e forte compromisso com a excelência. A ambição é crescer, ampliar a presença no mercado e continuar a criar valor para clientes e parceiros.","story.mark":"Melhoria contínua",
"clients.eyebrow":"Quem servimos","clients.title":"Soluções para operações que exigem confiança.","clients.c1.t":"Mineração & Indústria","clients.c1.d":"Serviços técnicos, apoio operacional e higienização de equipamentos e cabines.","clients.c2.t":"Transporte & Logística","clients.c2.d":"Higienização regular de frotas e manutenção de cabines de veículos de carga.","clients.c3.t":"Escritórios Corporativos","clients.c3.d":"Limpeza e desinfeção de ambientes de trabalho para saúde, conforto e produtividade.",
"cta.eyebrow":"Precise Planning Engenharia & Serviços","cta.title":"Excelência em cada serviço. Responsabilidade em cada solução.","cta.button":"Voltar ao topo","footer.rights":"Todos os direitos reservados."
},
en:{
"nav.about":"About","nav.services":"Services","nav.why":"Why us","nav.story":"Story","nav.clients":"Clients",
"hero.eyebrow":"Engineering • Services • Integrated Solutions","hero.title":"We turn challenges into practical solutions.","hero.text":"Technical, industrial and sanitation services focused on quality, safety, innovation and sustainability.","hero.cta1":"Explore our services","hero.cta2":"Who we are","hero.point1":"Quality","hero.point2":"Safety","hero.point3":"Sustainability","hero.badge":"Excellence in services",
"about.eyebrow":"Who we are","about.title":"A young, multidisciplinary company focused on results.","about.p1":"Precise Planning Engineering & Services, LDA (2PESL) is an innovative company created to turn challenges into opportunities through technology, technical knowledge and tailored solutions.","about.p2":"Our team is made up of dedicated professionals committed to excellence, agility, continuous improvement and quality management, serving customers, partners and suppliers responsibly.",
"mission.title":"Mission","mission.text":"Deliver high-quality services, operate responsibly and ethically, and continuously innovate to exceed customer expectations.","vision.title":"Vision","vision.text":"To be nationally recognized as a benchmark in our areas of expertise through service excellence and a commitment to corporate social responsibility.","values.title":"Values","values.text":"Transparency, excellence, professional development, sustainability, innovation, ethics and safety.",
"services.eyebrow":"What we do","services.title":"Integrated services for operations, infrastructure and workplaces.","services.intro":"2PESL combines engineering, operational support, trading and specialized sanitation services.",
"services.s1.t":"Mining Planning & Topography","services.s1.d":"Mining planning, reserve calculation, topography and technical services to optimize operations and productivity.","services.s2.t":"Construction & Infrastructure","services.s2.d":"Civil construction projects, electrical installation, civil and industrial plumbing and drainage, and metalwork.","services.s3.t":"Transport & Logistics","services.s3.d":"Cargo and passenger transport services with solutions adapted to each client’s needs.","services.s4.t":"Cleaning & Sanitation","services.s4.d":"Cleaning of offices, residences, vehicle cabins and equipment, including disinfection, odor neutralization and regular maintenance.","services.s5.t":"Special Hygiene Services","services.s5.d":"Antibacterial and antifungal treatments plus customized sanitation programs for companies and vehicle fleets.","services.s6.t":"Supplies & Trading","services.s6.d":"Office supplies, gardening, general trade, wholesale and retail, and import/export of miscellaneous goods.",
"clean.eyebrow":"Specialized sanitation","clean.title":"Cleaner, safer and more productive environments.","clean.text":"Our sanitation approach combines trained professionals, modern equipment and eco-conscious practices to deliver a high standard of cleanliness.","clean.a":"Deep cleaning of seats, panels and floors","clean.b":"Disinfection of high-touch surfaces","clean.c":"Cleaning workstations and common areas","clean.d":"Customized programs for companies and vehicle fleets",
"why.eyebrow":"Why 2PESL","why.title":"Differentiators that support service quality.","why.w1.t":"Specialized team","why.w1.d":"Trained and qualified professionals who deliver services efficiently and carefully.","why.w2.t":"Eco-conscious practices","why.w2.d":"Responsible use of products and practices that respect the environment and support sustainability.","why.w3.t":"Technology & innovation","why.w3.d":"Modern equipment, methods and solutions that improve effectiveness and speed.","why.w4.t":"Personalized service","why.w4.d":"Solutions tailored to the specific needs of each operation, customer and environment.",
"story.eyebrow":"Our story","story.title":"Growth built on commitment and excellence.","story.text":"Although 2PESL is a young company, its journey is already marked by achievements and a strong commitment to excellence. Our ambition is to grow, expand our market presence and continue creating value for customers and partners.","story.mark":"Continuous improvement",
"clients.eyebrow":"Who we serve","clients.title":"Solutions for operations that demand reliability.","clients.c1.t":"Mining & Industry","clients.c1.d":"Technical services, operational support, and sanitation of equipment and cabins.","clients.c2.t":"Transport & Logistics","clients.c2.d":"Regular fleet sanitation and maintenance of cargo vehicle cabins.","clients.c3.t":"Corporate Offices","clients.c3.d":"Cleaning and disinfection of workplaces to support health, comfort and productivity.",
"cta.eyebrow":"Precise Planning Engineering & Services","cta.title":"Excellence in every service. Responsibility in every solution.","cta.button":"Back to top","footer.rights":"All rights reserved."
}}
let lang='pt';
const langBtn=document.getElementById('langBtn');
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key]) el.textContent=translations[lang][key]});langBtn.querySelectorAll('span').forEach(s=>s.classList.toggle('active',s.textContent.toLowerCase()===lang));}
langBtn.addEventListener('click',()=>{lang=lang==='pt'?'en':'pt';applyLang()});
const menuBtn=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',window.scrollY>20),{passive:true});
document.getElementById('year').textContent=new Date().getFullYear();applyLang();
